### ISSUE TITLE
Help: Is it possible to use with embedded database and buffered insert?

### ISSUE THREAD

**Issue by selvavm** [roy-ganz/toql#5]
This is a fantastic work. I am not an expert in db and sql but your documentation is really easy to comprehend. 

I have been looking for similar crate a long time but not sure if yours fits my requirement. 

I have a for loop which loops through more than 10 million json files and I am using serde to convert each to struct. Then I am storing those structs in a HashMap. However, I am hitting out of memory due to size. If I can store all this, then I will be doing some aggregate function (say sum of spends in a restaurant and similarly sum of spends in fuel). 

Is it possible to have a on-the-fly temporary database (which is installed and initialised before the for loop and preferably nosql) to store structs using toql?. This will avoid HashMap and thus memory issues. Moreover, I wanted these inserts should be quicker (maybe caching/buffering to avoid waiting time) and is that possible? Note that, my file names are unique so there is no consistency issue with inserts.

**Comment by roy-ganz** [comment]
Hi selvavm, 
what kind of output should your program generate?
Without that information, I can't really give you any good advise.

Basically Toql gives you more comfort and flexibility to talk to databases than a "raw" driver. But you pay that with performance.  When you do number crunching, you don't wan't to pay that. Instead you should use a "raw" driver directly and call insert on it.

But maybe you don't need a database at all, depends on your program output.

**Comment by roy-ganz** [comment]
Hi, from what you told me and what I assume:

1. Your problem is memory pressure: Don't you a database, as it will use additional memory without being benefical for your case.
2. Your receipts are only needed to update your statistics. Update the statistics immediately after reading the file. Ensure that the receipts are not saved and discarded after the statistics are updated. 
3. Your receipts will contain a lot of fields, but only a few are probably needed for your statistics. Ensure that serde does only read the fields you're interested in. Dont't map fields that you are not interested in.
4. If the individual files are very big then your use of serde may be not optimized or serde might not be the right tool at all. See [this reddit](https://www.reddit.com/r/rust/comments/hx09kd/help_parsing_a_really_large_22gb_json_file/).

Hope that helps.
I'm closing this issue as relevance to Toql has been resolved.
